allowBuilds:
  pnpm: false
minimumReleaseAgeExclude:
  - '@shikijs/core@4.1.0'
  - '@shikijs/engine-javascript@4.1.0'
  - '@shikijs/engine-oniguruma@4.1.0'
  - '@shikijs/langs@4.1.0'
  - '@shikijs/markdown-it@4.1.0'
  - '@shikijs/primitive@4.1.0'
  - '@shikijs/themes@4.1.0'
  - '@shikijs/types@4.1.0'
  - shiki@4.1.0
  - taze@19.13.0
  - pnpm@11.13.1
  - '@vue/compiler-core@3.5.40'
  - '@vue/compiler-dom@3.5.40'
  - '@vue/compiler-sfc@3.5.40'
  - '@vue/compiler-ssr@3.5.40'
  - '@vue/reactivity@3.5.40'
  - '@vue/runtime-core@3.5.40'
  - '@vue/runtime-dom@3.5.40'
  - '@vue/server-renderer@3.5.40'
  - '@vue/shared@3.5.40'
  - vue-router@5.2.0
  - vue@3.5.40
